### ISSUE TITLE
seems authenticate fails now.

### ISSUE THREAD

**Issue by FredJiang0324** [Syzygianinfern0/Texas-DPS-Scheduler#1]
It run well yesterday night, when I tried to run it today, the traceback shows as below:

Traceback (most recent call last):
  File "/workspaces/Texas-DPS-Scheduler/main.py", line 186, in <module>
    main()
  File "/workspaces/Texas-DPS-Scheduler/main.py", line 53, in main
    headers=auth.get_headers(reauth=True),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Texas-DPS-Scheduler/fingerprints.py", line 93, in get_headers
    self._authenticate()
  File "/workspaces/Texas-DPS-Scheduler/fingerprints.py", line 86, in _authenticate
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate

**Comment by Syzygianinfern0** [comment]
I just tried it and it works fine for me.

You could try to turn off the headless flag for selenium (if you're running this locally) to see whats up
https://github.com/Syzygianinfern0/Texas-DPS-Scheduler/blob/8f3a5ecb1f00a0ac8167e4d795299fee3983d0f3/fingerprints.py#L41

**Comment by Syzygianinfern0** [comment]
@FredJiang0324 did you get to try this?

**Comment by FredJiang0324** [comment]
Wonderful work! But have went to a DPS 2 hours away from my home and get
the appointment. I will try to run this code later. Thanks for your
contribution to Texas community LOL.

**Comment by alvinbabujohn** [comment]
Can confirm turning off headless worked for me (WSL2 on W11).

**Comment by Syzygianinfern0** [comment]
Keeping the `headless` flag on should be fine as well. 

There are occasional errors (about once per hour based on my experience), but they're expected. It's difficult to bypass the new authentication system _every time_, but it works out most times. Since `monitor.py` triggers the main script each minute, this ends up working to our advantage.

Thanks for being one of the first people to test this out!
